version: "3.7"
services:
  influxdb:
    image: influxdb:1.4.2
    volumes:
      - influxdb:/var/lib/influxdb

  mongo:
    image: mongo:4.1.10
    volumes:
      - mongo:/data/db

  rabbitmq:
    image: pedroalvesferreira/rabbitmq-with-web-mqtt
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15675:15675"

  list_server:
    build: ./server/
    ports:
      - "8080:8080"
      - "3030:3030"
    environment:
        - EBU_LIST_WEB_APP_DOMAIN=http://172.18.0.4:8080
        - EBU_LIST_LIVE_MODE=${EBU_LIST_LIVE_MODE}
        - EBU_LIST_CAPTURE_INTERFACE=${EBU_LIST_CAPTURE_INTERFACE}
        - EBU_LIST_RAMDISK=${EBU_LIST_RAMDISK}
        - EBU_LIST_DUMP_SERVER_ADDR=http://172.18.0.1:3000
    links:
      - influxdb
      - mongo
      - rabbitmq
    volumes:
      - listserver:/home/
      - type: bind
        source: /media/ramdisk
        target: /app/listwebserver/ramdisk

volumes:
  mongo:
  listserver:
  influxdb:
