version: "3.7"
services:
  influxdb:
    image: influxdb:1.4.2
    volumes:
      - influxdb:/var/lib/influxdb

  mongo:
    image: mongo:4.1.10
    volumes:
      - mongo:/data/db

  list_server:
    build: ./server/
    ports:
      - "8080:8080"
      - "3030:3030"
    environment:
        - EBU_LIST_WEB_APP_DOMAIN=${EBU_LIST_WEB_APP_DOMAIN}
        - EBU_LIST_LIVE_MODE=${EBU_LIST_LIVE_MODE}
        - EBU_LIST_CAPTURE_INTERFACE=${EBU_LIST_CAPTURE_INTERFACE}
        - EBU_LIST_RAMDISK=${EBU_LIST_RAMDISK}
        - EBU_LIST_DUMP_SERVER_ADDR=${EBU_LIST_DUMP_SERVER_ADDR}
    links:
      - influxdb
      - mongo
    volumes:
      - listserver:/home/
      - type: bind
        source: /media/ramdisk
        target: /app/listwebserver/ramdisk

volumes:
  mongo:
  listserver:
  influxdb:
